name: CI/CD .NET API to EC2

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.116'

    - name: Restore dependencies
      run: dotnet restore ProyectoMetodologia/ProyectoMetodologia.csproj

    - name: Build project
      run: dotnet build ProyectoMetodologia/ProyectoMetodologia.csproj --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.116'

    - name: Run tests
      run: dotnet test --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.116'

    - name: Publish app
      run: dotnet publish ProyectoMetodologia/ProyectoMetodologia.csproj -c Release -o ./publish

    - name: Deploy to EC2 via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        source: "./publish"
        target: "~/proyecto-api"
